version: '3'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_VERSION=14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: Free
      POSTGRES_PASSWORD: Willy
    volumes:
      - "./postgres/init:/docker-entrypoint-initdb.d"
