version: '3'

services:
  server:
    image: cimg/base:current
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://Free:Willy@db:5432/wiki
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: Free
      PGRST_OPENAPI_SERVER_PROXY_URI: "http://127.0.0.1:3000"
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - POSTGRES_VERSION=14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: wiki
      POSTGRES_USER: Free
      POSTGRES_PASSWORD: Willy
    volumes:
      - "./postgres/init:/docker-entrypoint-initdb.d"
