version: 2.1

executors:
  docker-postgres:
    docker:
      - image: cimg/base:current
      - image: postgres:11-alpine-ram
      - image: postgres:11-alpine-ram
        name: bigbird
    resource_class: large

jobs:
  test:
    executor: docker-postgres
    steps:
      - checkout

workflows:
  main:
    jobs:
      - test
